### PR TITLE
cast boolean string true or false

### PR DESCRIPTION
**Pull request by pdornfel**

### CODE REVIEW

**Comment by pdornfel** [comment]
@dwaller any way to get this merged in? I would prefer to have the gem i'm working on point to your gem rather than a git repo.

**Comment by dwaller** [comment]
This change seems reasonable - very similar to the 't' and 'f' values that it currently supports.  I'd be happy to merge this in, but it needs tests and an update to the readme to document the new behaviour.  

I've just fixed the travis build (one of the development dependencies gems started objecting to certain Ruby versions) in master so if you merge/rebase that in then you should have passing tests to work from.

**Comment by pdornfel** [comment]
@dwaller should be all set 👍

**Comment by dwaller** [comment]
Released as gem v3.1.0

**Pull request merged**
