### PR TITLE
Support Floats, with Accompanying Specs

### PR DESCRIPTION
**Pull request by kjrocker**
I can't take any real credit for this PR. Found this useful addition in one of the project forks, and wanted to bring it over.

### CODE REVIEW

**Comment by kjrocker** [comment]
@fastdivision Seeing as this PR is your work more than mine, want to confirm there's nothing you'd oppose in the CLA.

**Comment by fastdivision** [comment]
@kjrocker Fine with me, thanks for checking!

**Comment by dwaller** [comment]
Totally happy with the principal of this change.  Can you fix up those failing asserts by using `kind_of(Integer)`?  That should work on both Ruby 2.4 and older Rubies.

**Comment by dwaller** [comment]
Thanks for your contribution @kjrocker @fastdivision.  Did you complete the Contribution License Agreement at https://cla.microsoft.com?  (Sorry, it's a pain, but at least Microsoft are supportive of open source project now.)  

I'll cut a new gem soon.

**Comment by fastdivision** [comment]
@dwaller CLA signed, thanks for the quick follow-up!

**Comment by dwaller** [comment]
Version 3.2 pushed to rubygems just now.

**Comment by kjrocker** [comment]
My first open source contribution! :D

**Pull request merged**
